// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwcvvohlmueeuvaqfaqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53Y3Z2b2hsbXVlZXV2YXFmYXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3NzEyNzYsImV4cCI6MjA4NjM0NzI3Nn0.nDxZ_9AJV9FDkBiZtbpTRHANJ1rp7OnKVtgP9tpoFos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});